services:
  post_db:
    image: mongo:3.2
    volumes:
      - post_db/data/db
    networks:
      - monitoring
  
  ui:
    image: место образа
    enviroment:
      - POST_SERVICE_HOST=post
      - POST_SERVICE_PORT=5000
      - COMMENT_SERVICE_HOST=comment
      - COMMENT_SERVICE_PORT=9292
    ports:
      - 9292:9292/tcp
    depends_on:
      - comment
      - post
    networks:
      - monitoring

  post:
    image: место образа
    enviroment:
      - POST_DATABASE_HOST=post_db
      - POST_DATABASE=posts
    depends_on:
      - post_db
    ports:
      -"5000:5000"
    networks:
      - monitoring

  comment:
    image: место образа
    enviroment:
      - COMMENT_DATABASE_HOST=post_db
      - COMMENT_DATABASE=comments
    depends_on:
      - post_db
    networks:
      - monitoring
  volumes:
    post_db
  
  networks:
    monitoring:

  # Monitoring services
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - reddit_net

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
      - ./provisioning:/etc/grafana/provisioning
      - ./dashboards:/etc/grafana/dashboards
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - reddit_net

  cadvisor:
    image: google/cadvisor
    ports:
      - "8080:8080"
    networks:
      - reddit_net

  blackbox_exporter:
    image: prom/blackbox-exporter
    ports:
      - "9115:9115"
    networks:
      - reddit_net

networks:
  reddit_net:
    driver: bridge

volumes:
  grafana-data:
