global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'reddit_services'
    static_configs:
      - targets:
          - 'ui:9292'
          - 'post:5000'
          - 'comment:9292'

  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
          - http://ui:9292/
          - http://ui:9292/new
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox_exporter:9115
