apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-wordpress-config
data:
  WORDPRESS_DB_HOST: {{ .Release.Name }}-mysql:3306
  WORDPRESS_DB_NAME: {{ .Values.mysql.databaseName }}
  WORDPRESS_DB_USER: root
