apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-wordpress
spec:
  replicas: {{ .Values.wordpress.replicaCount }}
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
        - name: wordpress
          image: {{ .Values.wordpress.image }}
          env:
            - name: WORDPRESS_DB_HOST
              value: {{ .Release.Name }}-mysql:3306
            - name: WORDPRESS_DB_NAME
              value: {{ .Values.mysql.databaseName }}
            - name: WORDPRESS_DB_USER
              value: root
            - name: WORDPRESS_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-wordpress-secret
                  key: mysql-password
          ports:
            - containerPort: 80
          volumeMounts:
            - name: wordpress-persistent-storage
              mountPath: /var/www/html
      volumes:
        - name: wordpress-persistent-storage
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-wordpress-pvc
